routes/web.php
<?php

use App\Http\Controllers\CarController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\DailyProductionController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DefaultController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\PosController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\PurchaseController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\TransactionController;
use App\Http\Controllers\UnitController;
use App\Http\Controllers\UserController;
use App\Models\DailyProduction;
use App\Models\Product;
use App\Models\Transaction;
use App\Models\Unit;
use App\Models\User;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('auth/login');
});

Route::get('/dashboard', [DashboardController::class, 'index'])->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {

    // 'middleware' => ['role:admin']
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::get('/profile/settings', [ProfileController::class, 'settings'])->name('profile.settings');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

    // Daily Production
    Route::resource('/daily_productions', DailyProductionController::class);

    Route::group(['middleware' => ['role:admin']], function() {
        // Units
        Route::resource('/cars', CarController::class);
        
        // User Management
        Route::resource('/users', UserController::class)->except(['show']);
        Route::put('/user/change-password/{username}', [UserController::class, 'updatePassword'])->name('users.updatePassword');
    });

});

require __DIR__.'/auth.php';

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use App\Models\DailyProduction;
use App\Models\Product;
use App\Models\Unit;
use App\Models\User;

class DashboardController extends Controller
{
    public function index()
    {
        $data_total_price = [];
        $data_total_month = [];
        $month = [1,2,3,4,5,6,7,8,9,10,11,12];

        $user = User::find(auth()->user()->id);

        if($user->hasRole('admin')){
            $count_unit = Unit::count();
            $count_product = Product::count();
            $total_sum = DailyProduction::sum('total_price');
            $count_user = User::count();
        
            $date = DailyProduction::select('date_assign')->whereNotNull('total_price')->distinct()->pluck('date_assign')->take(10)->toArray();

            foreach($date as $item)
                array_push($data_total_price,DailyProduction::select('total_price')->where('date_assign',$item)->sum('total_price'));
        
            foreach($month as $item)
                array_push($data_total_month,DailyProduction::select('total_price')->whereMonth('date_assign',$item)->sum('total_price') ?? 0);
        
            return view('dashboard.index',[
                'count_unit' => $count_unit,
                'count_product' => $count_product,
                'total_sum' =>  $total_sum,
                'count_user' =>  $count_user,
                'data_date' => '"'.implode('","', $date).'"',
                'data_total_price' => implode(",", $data_total_price),
                'data_total_price_month' => implode(",",$data_total_month ),
            ]);
        }
        elseif($user->hasRole('worker')){

            $count_product_assign = DailyProduction::where('user_id',auth()->user()->id)->sum('stock_assign');
            $count_product_sell = DailyProduction::where('user_id',auth()->user()->id)->sum('stock_sell');
            $count_product_return = DailyProduction::where('user_id',auth()->user()->id)->sum('stock_return');
            $total_sum = DailyProduction::where('user_id',auth()->user()->id)->sum('total_price');

            $date = DailyProduction::select('date_assign')->where('user_id',auth()->user()->id)
                                    ->whereNotNull('total_price')
                                    ->distinct()->pluck('date_assign')
                                    ->take(10)->toArray();

            foreach($date as $item)
                array_push($data_total_price,DailyProduction::select('total_price')->where('user_id',auth()->user()->id)->where('date_assign',$item)->sum('total_price'));

            foreach($month as $item)
                array_push($data_total_month,DailyProduction::select('total_price')->where('user_id',auth()->user()->id)->whereMonth('date_assign',$item)->sum('total_price') ?? 0);
            
            return view('dashboard.index',[
                'count_product_assign' => $count_product_assign,
                'count_product_sell' => $count_product_sell,
                'count_product_return' => $count_product_return,
                'total_sum' => $total_sum,
                'data_date' => '"'.implode('","', $date).'"',
                'data_total_price' => implode(",", $data_total_price),
                'data_total_price_month' => implode(",",$data_total_month ),
            ]);
        }
    }
}

resources/views/dashboard/body/footer.blade.php
<footer class="footer-admin mt-auto footer-light">
    <div class="container-xl px-4">
        <div class="row">
            <div class="col-md-6 small">Copyright © Car Rental <script>document.write(new Date().getFullYear())</script></div>
            <div class="col-md-6 text-md-end small">
                <a href="#">Privacy Policy</a>
                ·
                <a href="#">Terms &amp; Conditions</a>
            </div>
        </div>
    </div>
</footer>

resources/views/dashboard/body/header.blade.php
<nav class="topnav navbar navbar-expand shadow justify-content-between justify-content-sm-start navbar-light bg-white" id="sidenavAccordion">
    <!-- Sidenav Toggle Button-->
    <button class="btn btn-icon btn-transparent-dark order-1 order-lg-0 me-2 ms-lg-2 me-lg-0" id="sidebarToggle"><i data-feather="menu"></i></button>
    <!-- Navbar Brand-->
    <!-- * * Tip * * You can use text or an image for your navbar brand.-->
    <!-- * * * * * * When using an image, we recommend the SVG format.-->
    <!-- * * * * * * Dimensions: Maximum height: 32px, maximum width: 240px-->
    <a class="navbar-brand pe-3 ps-4 ps-lg-2" href="{{ route('dashboard') }}">Car Rental</a>
    <!-- Navbar Search Input-->
 
    <!-- Navbar Items-->
    <ul class="navbar-nav align-items-center ms-auto">
        <!-- User Dropdown-->
        <div class="btn btn-primary btn-sm" style="margin-right:2em;">{{ auth()->user()->name }}</div>
        <li class="nav-item dropdown no-caret dropdown-user me-3 me-lg-4">
            <a class="btn btn-icon btn-transparent-dark dropdown-toggle" id="navbarDropdownUserImage" href="javascript:void(0);" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <img class="img-fluid" src="{{ auth()->user()->photo ? asset('storage/profile/'.auth()->user()->photo) : asset('assets/img/illustrations/profiles/profile-1.png') }}" /></a>
            <div class="dropdown-menu dropdown-menu-end border-0 shadow animated--fade-in-up" aria-labelledby="navbarDropdownUserImage">
                <h6 class="dropdown-header d-flex align-items-center">
                    <img class="dropdown-user-img" src="{{ auth()->user()->photo ? asset('storage/profile/'.auth()->user()->photo) : asset('assets/img/illustrations/profiles/profile-1.png') }}" />
                    <div class="dropdown-user-details">
                        <div class="dropdown-user-details-name">{{ auth()->user()->name }}</div>
                        <div class="dropdown-user-details-email">{{ auth()->user()->email }}</a></div>
                    </div>
                </h6>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{{ route('profile.edit') }}">
                    <div class="dropdown-item-icon"><i data-feather="settings"></i></div>
                    Account
                </a>

                <!-- Logout -->
                <form action="{{ route('logout') }}" method="POST" id="logout-form">
                    @csrf
                    <button id="logout-button" class="dropdown-item" type="button">
                        <div class="dropdown-item-icon"><i data-feather="log-out"></i></div>
                        Logout
                    </button>
                </form>
            </div>
        </li>
    </ul>
</nav>

@push('js')
    <script>
       $('#logout-button').click(function(){
           Swal.fire({
               title: 'Are you sure you want to logout?',
               text: "Safe journey out there!",
               icon: 'warning',
               showCancelButton: true,
               confirmButtonColor: '#3085d6',
               cancelButtonColor: '#d33',
               confirmButtonText: 'Yes'
               }).then((result) => {
               if (result.isConfirmed) {
                   $('#logout-form').submit();
               }
           })

       });

    </script>
@endpush

resources/views/dashboard/body/main.blade.php
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Dashboard Inventory</title>

        <!-- Favicon -->
        <link rel="icon" type="image/x-icon" href="{{ asset('assets/img/favicon.png') }}" />

        <!-- Styles CSS -->
        <link href="{{ asset('assets/css/styles.css') }}" rel="stylesheet" />

        <!-- Icons -->
        <script data-search-pseudo-elements="" defer="" src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/js/all.min.js" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.28.0/feather.min.js" crossorigin="anonymous"></script>

        <script src="{{ asset('js/jquery.min.js') }}"></script>
        <script src="{{ asset('js/inputmask.min.js') }}"></script>
        <script src="{{ asset('js/sweetalert.min.js') }}"></script>
        
        <!-- Custom CSS for specific page.  -->
        @yield('specificpagestyles')
    </head>

    <body class="nav-fixed">
        <!-- BEGIN: Navbar Brand -->
        @include('dashboard.body.header')
        <!-- END: Navbar Brand -->

        <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                <!-- BEGIN: Sidenav -->
                @include('dashboard.body.sidebar')
                <!-- END: Sidenav -->
            </div>


            <div id="layoutSidenav_content">
                <main>
                <!-- BEGIN: Content -->
                    @yield('content')
                <!-- END: Content -->
                </main>

                <!-- BEGIN: Footer  -->
                @include('dashboard.body.footer')
                <!-- END: Footer  -->
            </div>
        </div>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="{{ asset('assets/js/scripts.js') }}"></script>

        <!-- Custom JS for specific page.  -->
        @yield('specificpagescripts')
    </body>
</html>
@stack('js')

resources/views/dashboard/body/sidebar.blade.php
<nav class="sidenav shadow-right sidenav-light">
    <div class="sidenav-menu">
        <div class="nav accordion" id="accordionSidenav">
            <!-- Sidenav Menu Heading (Core)-->
            <div class="sidenav-menu-heading">Core</div>
            <a class="nav-link {{ Request::is('dashboard*') ? 'active' : '' }}" href="{{ route('dashboard') }}">
                <div class="nav-link-icon"><i data-feather="activity"></i></div>
                Dashboard
            </a>

            @role('admin')
                <!-- Sidenav Heading (Settings)-->
                <div class="sidenav-menu-heading">Settings</div>
                <a class="nav-link {{ Request::is('users*') ? 'active' : '' }}" href="{{ route('users.index') }}">
                    <div class="nav-link-icon"><i class="fa-solid fa-users"></i></div>
                    Users
                </a>
                <a class="nav-link {{ Request::is('cars*') ? 'active' : '' }}" href="{{ route('cars.index') }}">
                    <div class="nav-link-icon"><i class="fa-solid fa-car"></i></div>
                    Car
                </a>
            @endrole

        </div>
    </div>

</nav>