routes/web.php
<?php

use App\Http\Controllers\CarController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\DailyProductionController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DefaultController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\PosController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\PurchaseController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\TransactionController;
use App\Http\Controllers\UnitController;
use App\Http\Controllers\UserController;
use App\Models\DailyProduction;
use App\Models\Product;
use App\Models\Transaction;
use App\Models\Unit;
use App\Models\User;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('auth/login');
});

Route::get('/dashboard', [DashboardController::class, 'index'])->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {

    // 'middleware' => ['role:admin']
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::get('/profile/settings', [ProfileController::class, 'settings'])->name('profile.settings');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

    // Daily Production
    Route::resource('/daily_productions', DailyProductionController::class);

    Route::group(['middleware' => ['role:admin']], function() {
        // Units
        Route::resource('/cars', CarController::class);
        
        // User Management
        Route::resource('/users', UserController::class)->except(['show']);
        Route::put('/user/change-password/{username}', [UserController::class, 'updatePassword'])->name('users.updatePassword');
    });

});

require __DIR__.'/auth.php';

app/Models/Car.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Kyslik\ColumnSortable\Sortable;

class Car extends Model
{
    use HasFactory, Sortable;
    
    protected $fillable = [
        'name',
        'slug',
    ];

    protected $sortable = [
        'name',
        'slug',
    ];

    protected $guarded = [
        'id',
    ];

    public function scopeFilter($query, array $filters)
    {
        $query->when($filters['search'] ?? false, function ($query, $search) {
            return $query->where('name', 'like', '%' . $search . '%');
        });
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }
}

app/Http/Controllers/CarController.php
<?php

namespace App\Http\Controllers;

use App\Models\Car;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Redirect;

class CarController extends Controller
{
    public function index()
    {
        $row = (int) request('row', 10);
        if ($row < 1 || $row > 100) 
            abort(400, 'The per-page parameter must be an integer between 1 and 100.');
        
        $cars = Car::filter(request(['search']))
                ->sortable()
                ->paginate($row)
                ->appends(request()->query());

        return view('cars.index', [
            'cars' => $cars,
        ]);
    }

    public function create()
    {
        return view('cars.create');
    }

    public function store(Request $request)
    {
        $rules = [
            'name' => 'required',
            'slug' => 'required',
        ];
        $validatedData = $request->validate($rules);

        try {
            DB::beginTransaction();

            Car::create($validatedData);

            DB::commit();
            return Redirect::route('cars.index')->with('success', 'Unit has been created!');

        } catch (\Throwable $th) {
            DB::rollback();
            return Redirect::route('cars.create')
                ->with('failed-transaction', 'Unit cannot been created');
        }
    }

    public function show(Car $cats)
    {
      abort(404);
    }

    public function edit(Car $car)
    {
        return view('cars.edit', [
            'car' => $car
        ]);
    }

    public function update(Request $request, Car $car)
    {
        $rules = [
                'name' => 'required',
                'slug' => 'required',
            ];
        $validatedData = $request->validate($rules);

        try {
            DB::beginTransaction();

            Car::where('slug', $car->slug)->update($validatedData);

            DB::commit();
            return Redirect::route('cars.index')->with('success-updated', 'Car has been updated!');

        } catch (\Throwable $th) {
            DB::rollback();
            return Redirect::route('cars.edit',$car)
                ->with('failed-transaction', 'Car cannot been updated');
        }
    }


    public function destroy(Car $car)
    {
        try {
            DB::beginTransaction();

            Car::destroy($car->id);

            DB::commit();
            return Redirect::route('cars.index')->with('success-deleted', 'Unit has been deleted!');
        } catch (\Throwable $th) {
            DB::rollback();
            return Redirect::route('cars.index')
                ->with('failed-transaction', 'Unit cannot been deleted because other PRODUCT refer to this UNIT!');
        }
    }
}

resources/views/cars/create.blade.php
@extends('dashboard.body.main')

@section('content')
<header class="page-header page-header-dark bg-warning pb-10">
    <x-header.main title="Add Unit" icon="fa-solid fa-car" >
        <x-slot name="navigation">
            <x-header.navigation title="Dashboard" path="dashboard" />
            <x-header.navigation title="Car" path="cars.index" last="Create"  />
        </x-slot>
    </x-header.main>   
    <x-notification.alert />
</header>

<div class="container-xl px-2 mt-n10">
    <form action="{{ route('cars.store') }}" method="POST" id="car-submit-form">
        @csrf
     
        <x-card.main title="Car Detail" >
            <x-slot name="body">
                <div class="row">
                    <div class="col-md-12 mb-3">
                        <x-form.text title="Car Name" model="name" required />
                    </div>
                    <div class="col-md-12 mb-3">
                        <x-form.text title="Car Slug (non editable)." model="slug" readonly />
                    </div>
                    <div class="col-md-12">
                        <button id="car-submit" class="btn btn-primary" type="button" >Add</button>
                        <a class="btn btn-danger" href="{{ route('cars.index') }}">Cancel</a>
                    </div>
                </div>
            </x-slot>
        </x-card.main>
    </form>
</div>

<script>
    // Slug Generator
    const title = document.querySelector("#name");
    const slug = document.querySelector("#slug");
    title.addEventListener("keyup", function() {
        let preslug = title.value;
        preslug = preslug.replace(/ /g,"-");
        slug.value = preslug.toLowerCase()+'-car-rent';
    });
</script>
@endsection

@push('js')
    <script>
        $('#car-submit').click(function (e) {
            e.preventDefault();
            Swal.fire({
                title: 'Do you want to save the changes?',
                showCancelButton: true,
                confirmButtonText: 'Save',
                }).then((result) => {
                if (result.isConfirmed) {
                    $('#car-submit-form').submit();
                }else {
                    Swal.fire('Changes are not saved', '', 'info')
                }
            })
        });
    </script>
@endpush

resources/views/cars/edit.blade.php
@extends('dashboard.body.main')

@section('content')
<header class="page-header page-header-dark bg-warning pb-10">
    <x-header.main title="Edit Car" icon="fa-solid fa-car" >
        <x-slot name="navigation">
            <x-header.navigation title="Dashboard" path="dashboard" />
            <x-header.navigation title="Cars" path="cars.index" last="Edit"  />
        </x-slot>
    </x-header.main>   
    <x-notification.alert />
</header>

<div class="container-xl px-2 mt-n10">
    <form action="{{ route('cars.update', $car->slug) }}" method="POST" id="car-submit-form">
        @csrf
        @method('put')

        <x-card.main title="Car Detail" >
            <x-slot name="body">
                <div class="row">
                    <div class="col-md-12 mb-3">
                        <x-form.text title="Car Name" model="name" data="{{ $car->name }}" required />
                    </div>
                    <div class="col-md-12 mb-3">
                        <x-form.text title="Car Slug (non editable)." model="slug" data="{{ $car->slug }}" readonly />
                    </div>
                    <div class="col-md-12">
                        <button id="car-submit" class="btn btn-primary" type="button">Update</button>
                        <a class="btn btn-danger" href="{{ route('cars.index') }}">Cancel</a>
                    </div>
                </div>
            </x-slot>
        </x-card.main>
    </form>
</div>

<script>
    // Slug Generator
    const title = document.querySelector("#name");
    const slug = document.querySelector("#slug");
    title.addEventListener("keyup", function() {
        let preslug = title.value;
        preslug = preslug.replace(/ /g,"-");
        slug.value = preslug.toLowerCase()+'-car-rent';
    });
</script>
@endsection

@push('js')
    <script>
        $('#car-submit').click(function (e) {
            e.preventDefault();
            Swal.fire({
                title: 'Do you want to save the changes?',
                showCancelButton: true,
                confirmButtonText: 'Save',
                }).then((result) => {
                if (result.isConfirmed) {
                    $('#car-submit-form').submit();
                }else {
                    Swal.fire('Changes are not saved', '', 'info')
                }
            })
        });
    </script>
@endpush

resources/views/cars/index.blade.php
@extends('dashboard.body.main')

@section('content')
<header class="page-header page-header-dark bg-warning pb-10">
    <x-header.main title="Car List" icon="fa-solid fa-car" >
        <x-slot name="path">
            <x-header.path title="Add" path="cars.create" icon="fa-solid fa-plus me-3" class="btn btn-primary add-list" />
            <x-header.path title="Clear Search" path="cars.index" icon="fa-solid fa-trash me-3" class="btn btn-danger add-list" />
        </x-slot>

        <x-slot name="navigation">
            <x-header.navigation title="Dashboard" path="dashboard" last="Cars"  />
        </x-slot>
    </x-header.main>   
    <x-notification.alert />
</header>

<!-- BEGIN: Main Page Content -->
<div class="container px-2 mt-n10">
    <div class="card mb-4">
        <div class="card-body">
            <div class="row mx-n4">
                <div class="col-lg-12 card-header mt-n4">
                    <form action="{{ route('cars.index') }}" method="GET">
                        <div class="d-flex flex-wrap align-items-center justify-content-between">
                            <div class="form-group row align-items-center">
                                <label for="row" class="col-auto">Row:</label>
                                <div class="col-auto">
                                    <select class="form-control" name="row">
                                        <option value="10" @if(request('row') == '10')selected="selected"@endif>10</option>
                                        <option value="25" @if(request('row') == '25')selected="selected"@endif>25</option>
                                        <option value="50" @if(request('row') == '50')selected="selected"@endif>50</option>
                                        <option value="100" @if(request('row') == '100')selected="selected"@endif>100</option>
                                    </select>
                                </div>
                            </div>

                            <div class="form-group row align-items-center justify-content-between">
                                <label class="control-label col-sm-3" for="search">Search:</label>
                                <div class="col-sm-8">
                                    <div class="input-group">
                                        <input type="text" id="search" class="form-control me-1" name="search" placeholder="Search car" value="{{ request('search') }}">
                                        <div class="input-group-append">
                                            <button type="submit" class="input-group-text bg-primary"><i class="fa-solid fa-magnifying-glass font-size-20 text-white"></i></button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>

                <hr>

                <div class="col-lg-12">
                    <div class="table-responsive">
                        <table class="table table-striped">
                            <thead class="thead-light">
                                <tr>
                                    <th scope="col">No.</th>
                                    <th scope="col">@sortablelink('name', 'Car Name')</th>
                                    <th scope="col">@sortablelink('slug', 'Car Slug')</th>
                                    <th scope="col">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($cars as $key => $car)
                                <tr>
                                    <th scope="row">{{ (($cars->currentPage() * (request('row') ? request('row') : 10)) - (request('row') ? request('row') : 10)) + $loop->iteration  }}</th>
                                    <td>{{ $car->name }}</td>
                                    <td>{{ $car->slug }}</td>
                                    <td>
                                        <div class="d-flex">
                                            <a href="{{ route('cars.edit', $car) }}" class="btn btn-outline-primary btn-sm mx-1"><i class="fas fa-edit"></i></a>
                                            <form action="{{ route('cars.destroy', $car->slug) }}" method="POST" id="delete-car-form-{{ $key }}" >
                                                @csrf
                                                @method('delete')
                                                <button class="btn btn-outline-danger btn-sm" type="button" onclick="deleteCar({{ $key }})" >
                                                    <i class="far fa-trash-alt"></i>
                                                </button>
                                            </form>
                                        </div>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>

                {{ $cars->links() }}
            </div>
        </div>
    </div>
</div>
<!-- END: Main Page Content -->
@endsection

@push('js')
    <script>
        function deleteCar(index)
        {
            Swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
                }).then((result) => {
                if (result.isConfirmed) {
                    $('#delete-car-form-'+index).submit();
                }
            })
        }
    </script>
@endpush